//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace book
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_tahvil
    {
        public int ID { get; set; }
        public int idbook { get; set; }
        public int idcustomer { get; set; }
        public string tahvil_date { get; set; }
        public string name_customer { get; set; }
        public string name_book { get; set; }
        public string family_customer { get; set; }
    }
}
