//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace book
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string family { get; set; }
        public string birth_data { get; set; }
        public string ozviat_date { get; set; }
        public int Idmely { get; set; }
        public string numerik_fhone { get; set; }
    }
}
